### ISSUE TITLE
UnhandledPromiseRejectionWarning error when selecting the dropdown using "selectOption" 

### ISSUE THREAD

**Issue by magimenon** [Codeception/CodeceptJS#295] opened 2016-11-17 21:46 UTC
#### What are you trying to achieve?
I'm trying to select an option from the dropdown. Name of my <select>  is "search" and I select a value "new". I get a below error:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to execute 'iterateNext' on 'XPathResult': The document has mutated since the result was returned.

One thing to be noted here is when I select the first dropdown there are other dropdown gets populated (ajax). I googled and couldn't figure out what's going wrong here?

#### What do you get instead?

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to execute 'iterateNext' on 'XPathResult': The document has mutated since the result was returned.

**Comment by sushan088** [comment] 2016-11-18 08:45
I am having the same problem. Previously it works fine with Webdriverio and phantomjs but after using nightmare, not working in that as well.

**Comment by DavertMik** [comment] 2016-11-18 12:33
Could you provide HTML which reproduces this error? 

Also what helper is that? Nightmare or webriverio?

**Comment by magimenon** [comment] 2016-11-18 17:42
Im using nightmare & node version 6.9.1

The HTML is - 

<form name="ContactUsForm">
    <p class="required"><span>*</span> = required</p>
    <fieldset repeat="content.form.fieldsets" name="messageInfo">
        <legend if="legend">Message</legend>
        <div each="fields" template="">
            <label class="  ">
                <span>Subject</span>
                <input type="text" data-which-field="" name="contact_subject" value="" maxlength="100" class="valid">
            </label>
            <label class="  ">
                <span>Message Text</span>
                <textarea name="customer:comments" wrap="" maxlength="2000"></textarea>
            </label>
        </div>
    </fieldset>
    <fieldset repeat="content.form.fieldsets" name="contactInfo">
        <legend if="legend">Contact Information</legend>
        <div each="fields" template="">
            <label class=" required ">
                <span>First Name</span>
                <input type="text" data-which-field="" name="contact:name:first" value="" maxlength="100" required="">
            </label>
            <label class=" required ">
                <span>Last Name</span>
                <input type="text" data-which-field="" name="contact:name:last" value="" maxlength="100" required="">
            </label>
            <label class="required ">
                <span if="label">Preferred Contact</span>
                <select name="preferred_contact" data-which-field="" required="" fieldtype="">
                    <option value="email" repeat="values">Email</option>
                    <option value="day" repeat="values">Phone</option>
                </select>
            </label>
            <label class=" required ">
                <span>Email</span>
                <input type="email" data-which-field="" name="contact:email" value="" maxlength="200" placeholder="user@mydomain.com" pattern="[A-Za-z0-9!#$%&amp;'*+/=?^_`{|}~-]+(?:\.[A-Za-z0-9!#$%&amp;'*+/=?^_`{|}~-]+)*@(?:[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?" required="">
            </label>
            <label class=" required ">
                <span>Phone</span>
                <input type="tel" data-which-field="" name="contact:phone:phone:day" value="" maxlength="" placeholder="(###) ###-####" pattern="(\(?[0-9]{3}\)?[\. -]?[0-9]{3}[\. -]?[0-9]{4})?$|^(\(?[0-9]{2}\)?[\. -]?[0-9]{4}[\. -]?[0-9]{4})?" required="">
            </label>
        </div>
    </fieldset>
    <fieldset repeat="content.form.fieldsets" name="default_section">
        <div each="fields" template="">
            <input aria-hidden="true" type="text" name="hp:contact:cmpny:phone" value=""><input type="hidden" name="cellName" value="contact_us"><input type="hidden" name="pageName" value="ContactUsForm"><input type="hidden" name="outputType" value="json"><input type="hidden" name="widgetType" value="emailforms"><input type="hidden" name="widgetName" value="contactUs_widget"><input type="hidden" name="productId" value="46.110.00"><input type="hidden" name="widgetContext" value=""><input type="hidden" name="source" value="">
        </div>
    </fieldset>

    <div role="status" id="search-view/card/7ecd6bc1-926e-4688-902e-13965f514926-status" aria-hidden="true">
        
    </div>
                    
    <div if="content.form.buttons" template="button" each="content.form.buttons">
        <button type="submit" name="" id="" data-action="formSubmit">Submit</button>
    </div>
</form>

**Comment by sushan088** [comment] 2016-11-19 04:06
For normal html dropdown it is working fine but I am using the semantic ui dropdown so it is throwing error on that part.

**Comment by magimenon** [comment] 2016-11-19 17:33
I'm using a normal html and it fails.

**Comment by DavertMik** [comment] 2016-11-22 22:16
Looks like we have 2 cases here. I can work only with that one with an example.
@magimenon could you provide your HTML code as well, so I could fix the issue and make a test for it?

**Comment by magimenon** [comment] 2016-11-22 22:20
```html
<form name="ContactUsForm">
    <p class="required"><span>*</span> = required</p>
    <fieldset repeat="content.form.fieldsets" name="messageInfo">
        <legend if="legend">Message</legend>`
        <div each="fields" template="">`
            <label class="  ">
                <span>Subject</span>
                <input type="text" data-which-field="" name="contact_subject" value="" maxlength="100" class="valid">
            </label>
            <label class="  ">
                <span>Message Text</span>
                <textarea name="customer:comments" wrap="" maxlength="2000"></textarea>
            </label>
        </div>
    </fieldset>
    <fieldset repeat="content.form.fieldsets" name="contactInfo">
        <legend if="legend">Contact Information</legend>
        <div each="fields" template="">
            <label class=" required ">
                <span>First Name</span>
                <input type="text" data-which-field="" name="contact:name:first" value="" maxlength="100" required="">
            </label>
            <label class=" required ">
                <span>Last Name</span>
                <input type="text" data-which-field="" name="contact:name:last" value="" maxlength="100" required="">
            </label>
            <label class="required ">
                <span if="label">Preferred Contact</span>
                <select name="preferred_contact" data-which-field="" required="" fieldtype="">
                    <option value="email" repeat="values">Email</option>
                    <option value="day" repeat="values">Phone</option>
                </select>
            </label>
        </div>
    </fieldset>
    <fieldset repeat="content.form.fieldsets" name="default_section">
        <div each="fields" template=""><!-- Revisit what honeypot is, hidden at the moment -->
            <input aria-hidden="true" type="text" name="hp:contact:cmpny:phone" value=""><!--^_^--><input type="hidden" name="cellName" value="contact_us"><!--^_^--><input type="hidden" name="pageName" value="ContactUsForm"><!--^_^--><input type="hidden" name="outputType" value="json"><input type="hidden" name="widgetType" value="emailforms"><!--^_^--><input type="hidden" name="widgetName" value="contactUs_widget"><!--^_^--><input type="hidden" name="productId" value="46.110.00"><!--^_^--><input type="hidden" name="widgetContext" value=""><!--^_^--><input type="hidden" name="source" value="">
        </div>
    </fieldset>
    <div role="status" id="search-view/card/7ecd6bc1-926e-4688-902e-13965f514926-status" aria-hidden="true">
    </div>
    <div if="content.form.buttons" template="button" each="content.form.buttons">
        <button type="submit" name="" id="" data-action="formSubmit">Submit</button>
    </div>
</form>
```

**Comment by sushan088** [comment] 2016-11-23 06:32
Please help me with this code as well.
<form method="POST" action="https://abc.com" accept-charset="UTF-8" id="clientForm" class="ui form clearfix novalidate" role="form" enctype="multipart/form-data"><input name="_token" type="hidden" value="RtAUgkznHbGAViwL4PquIVRlRDyGeb3ptW27V8Cf">
          <div class="tableWrapper formWidth">
  <div class="container-fluid">
    <div class="paddingBlock">
      <small class="text-muted"><i>* fields are mandatory.</i></small>
    </div>
  </div>
  <h4 class="bg-primary marginNone innerTitle">Personal Details</h4>
  <div class="formPage-lg">
    <div class="ui doubling stackable three column grid padded">
      <div class="column">
        <div class="required field ">
          <label for="first_name">First Name</label>
          <input name="first_name" type="text" id="first_name">
        </div>
      </div>
      <div class="column">
        <div class="required field ">
          <label for="last_name">Last Name</label>
          <input name="last_name" type="text" id="last_name">
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label for="dob">DOB</label>
          <div class="ui right labeled input">
            <input class="datepicker dob" autocomplete="off" readonly="readonly" name="dob" type="text" id="dob">
            <div class="ui basic label"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
            
      <div class="column">
        <div class="required field ">
          <label for="country">Country</label>
          <div class="ui search dropdown selection">
          <select id="country" name="country">
          <option value="1">Afghanistan [AFN]</option>
          <option value="2">Albania [ALL]</option>
          <option value="3">Antarctica []</option>
          <option value="4">Algeria [DZD]</option>
          <option value="5">American Samoa [USD]</option>
          <option value="6">Andorra [EUR]</option></select>
          <i class="dropdown icon"></i><input class="search" autocomplete="off" tabindex="0">
          <div class="text">Afghanistan [AFN]</div>
          <div class="menu transition hidden" tabindex="-1">
          <div class="item active selected" data-value="1">Afghanistan [AFN]</div>
          <div class="item" data-value="2">Albania [ALL]</div>
          <div class="item" data-value="3">Antarctica []</div>
          <div class="item" data-value="4">Algeria [DZD]</div>
          <div class="item" data-value="5">American Samoa [USD]</div>
          <div class="item" data-value="6">Andorra [EUR]</div></div></div>
        </div>
      </div>
      
  
  
    <div class="ui doubling stackable one column grid padded">
      <div class="column">
        <div class="field ">
          <label for="photo">Photo</label>
          <div>
            <input class="inputfile inputFileUpload" id="photoUpload" accept="image/*" name="photo" type="file">
            <label for="photoUpload">
              <i class="icon-upload"></i>&nbsp;
              <span>Choose a file</span>
              <span class="fileName">No File Chosen</span>
            </label>
            <div class="small text-muted">
              <strong>Preferred:</strong><br><strong>Resolution: </strong>200px x 100px, <strong>Size: </strong>less
              than 2MB
            </div>
          </div>
        </div>
      </div>
      <div class="column submitButtonMargin">
        <button type="submit" class="button blueButton" data-loading-text="Processing&nbsp;&nbsp;<i class='fa fa-circle-o-notch fa-spin'></i>">Save
        </button>
      </div>
    </div>
  </div>
</div>
          </form>

**Comment by magimenon** [comment] 2016-11-23 06:37
@sushan088 - Did you try using I.fillField(<name>,<value>) instead of I.selectOption(<name>,<value>)?

@DavertMik Btw, this issue happens only when we use the I.selectOption which in turns changes the DOM (ajax).

**Comment by magimenon** [comment] 2016-11-23 06:37
@sushan088 - Did you try using I.fillField(<name>,<value>) instead of I.selectOption(<name>,<value>)?

@DavertMik Btw, this issue happens only when we use the I.selectOption which in turns changes the DOM (ajax).

**Comment by sushan088** [comment] 2016-11-23 06:41
**# ### My html with semantic ui dropdown**

`<form method="POST" action="https://abc.com" accept-charset="UTF-8" id="clientForm" class="ui form clearfix novalidate" role="form" enctype="multipart/form-data"><input name="_token" type="hidden" value="RtAUgkznHbGAViwL4PquIVRlRDyGeb3ptW27V8Cf">
          <div class="tableWrapper formWidth">
  <div class="container-fluid">
    <div class="paddingBlock">
      <small class="text-muted"><i>* fields are mandatory.</i></small>
    </div>
  </div>
  <h4 class="bg-primary marginNone innerTitle">Personal Details</h4>
  <div class="formPage-lg">
    <div class="ui doubling stackable three column grid padded">
      <div class="column">
        <div class="required field ">
          <label for="first_name">First Name</label>
          <input name="first_name" type="text" id="first_name">
        </div>
      </div>
      <div class="column">
        <div class="required field ">
          <label for="last_name">Last Name</label>
          <input name="last_name" type="text" id="last_name">
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label for="dob">DOB</label>
          <div class="ui right labeled input">
            <input class="datepicker dob" autocomplete="off" readonly="readonly" name="dob" type="text" id="dob">
            <div class="ui basic label"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
            
      <div class="column">
        <div class="required field ">
          <label for="country">Country</label>
          <div class="ui search dropdown selection">
          <select id="country" name="country">
          <option value="1">Afghanistan [AFN]</option>
          <option value="2">Albania [ALL]</option>
          <option value="3">Antarctica []</option>
          <option value="4">Algeria [DZD]</option>
          <option value="5">American Samoa [USD]</option>
          <option value="6">Andorra [EUR]</option></select>
          <i class="dropdown icon"></i><input class="search" autocomplete="off" tabindex="0">
          <div class="text">Afghanistan [AFN]</div>
          <div class="menu transition hidden" tabindex="-1">
          <div class="item active selected" data-value="1">Afghanistan [AFN]</div>
          <div class="item" data-value="2">Albania [ALL]</div>
          <div class="item" data-value="3">Antarctica []</div>
          <div class="item" data-value="4">Algeria [DZD]</div>
          <div class="item" data-value="5">American Samoa [USD]</div>
          <div class="item" data-value="6">Andorra [EUR]</div></div></div>
        </div>
      </div>
      
  
  
    <div class="ui doubling stackable one column grid padded">
      <div class="column">
        <div class="field ">
          <label for="photo">Photo</label>
          <div>
            <input class="inputfile inputFileUpload" id="photoUpload" accept="image/*" name="photo" type="file">
            <label for="photoUpload">
              <i class="icon-upload"></i>&nbsp;
              <span>Choose a file</span>
              <span class="fileName">No File Chosen</span>
            </label>
            <div class="small text-muted">
              <strong>Preferred:</strong><br><strong>Resolution: </strong>200px x 100px, <strong>Size: </strong>less
              than 2MB
            </div>
          </div>
        </div>
      </div>
      <div class="column submitButtonMargin">
        <button type="submit" class="button blueButton" data-loading-text="Processing&nbsp;&nbsp;<i class='fa fa-circle-o-notch fa-spin'></i>">Save
        </button>
      </div>
    </div>
  </div>
</div>
</form>`

**Comment by sushan088** [comment] 2016-11-23 06:43
<form method="POST" action="https://abc.com" accept-charset="UTF-8" id="clientForm" class="ui form clearfix novalidate" role="form" enctype="multipart/form-data"><input name="_token" type="hidden" value="RtAUgkznHbGAViwL4PquIVRlRDyGeb3ptW27V8Cf">
          <div class="tableWrapper formWidth">
  <div class="container-fluid">
    <div class="paddingBlock">
      <small class="text-muted"><i>* fields are mandatory.</i></small>
    </div>
  </div>
  <h4 class="bg-primary marginNone innerTitle">Personal Details</h4>
  <div class="formPage-lg">
    <div class="ui doubling stackable three column grid padded">
      <div class="column">
        <div class="required field ">
          <label for="first_name">First Name</label>
          <input name="first_name" type="text" id="first_name">
        </div>
      </div>
      <div class="column">
        <div class="required field ">
          <label for="last_name">Last Name</label>
          <input name="last_name" type="text" id="last_name">
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label for="dob">DOB</label>
          <div class="ui right labeled input">
            <input class="datepicker dob" autocomplete="off" readonly="readonly" name="dob" type="text" id="dob">
            <div class="ui basic label"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
            
      <div class="column">
        <div class="required field ">
          <label for="country">Country</label>
          <div class="ui search dropdown selection">
          <select id="country" name="country">
          <option value="1">Afghanistan [AFN]</option>
          <option value="2">Albania [ALL]</option>
          <option value="3">Antarctica []</option>
          <option value="4">Algeria [DZD]</option>
          <option value="5">American Samoa [USD]</option>
          <option value="6">Andorra [EUR]</option></select>
          <i class="dropdown icon"></i><input class="search" autocomplete="off" tabindex="0">
          <div class="text">Afghanistan [AFN]</div>
          <div class="menu transition hidden" tabindex="-1">
          <div class="item active selected" data-value="1">Afghanistan [AFN]</div>
          <div class="item" data-value="2">Albania [ALL]</div>
          <div class="item" data-value="3">Antarctica []</div>
          <div class="item" data-value="4">Algeria [DZD]</div>
          <div class="item" data-value="5">American Samoa [USD]</div>
          <div class="item" data-value="6">Andorra [EUR]</div></div></div>
        </div>
      </div>
      
  
  
    <div class="ui doubling stackable one column grid padded">
      <div class="column">
        <div class="field ">
          <label for="photo">Photo</label>
          <div>
            <input class="inputfile inputFileUpload" id="photoUpload" accept="image/*" name="photo" type="file">
            <label for="photoUpload">
              <i class="icon-upload"></i>&nbsp;
              <span>Choose a file</span>
              <span class="fileName">No File Chosen</span>
            </label>
            <div class="small text-muted">
              <strong>Preferred:</strong><br><strong>Resolution: </strong>200px x 100px, <strong>Size: </strong>less
              than 2MB
            </div>
          </div>
        </div>
      </div>
      <div class="column submitButtonMargin">
        <button type="submit" class="button blueButton" data-loading-text="Processing&nbsp;&nbsp;<i class='fa fa-circle-o-notch fa-spin'></i>">Save
        </button>
      </div>
    </div>
  </div>
</div>
          </form>

**Comment by sushan088** [comment] 2016-11-23 11:32
@magimenon Not working by replacing I.selectoption with I.fillfield.

**Comment by sushan088** [comment] 2016-11-23 11:48
@magimenon thanxs it worked, it is troubling me so much now it is fixed thanx.

**Comment by DavertMik** [comment] 2017-02-25 08:45
I hope it is fixed by @robrkerr

**Closed by DavertMik** 2017-02-25 08:45 UTC
