### ISSUE TITLE
I.click() and I.checkOption() not clicking check box 

### ISSUE THREAD

**Issue by mathis7875** [Codeception/CodeceptJS#877] opened 2018-01-16 18:38 UTC
#### What are you trying to achieve?
when using I.click() or I.checkOption  to click in checkbox I get element bot found. I use CSS and xpath and it still returns the same thing.

I.click('//*[@id="access-checkbox0"]')

  I.click('#access-checkbox0');

  I.checkOption('#access-checkbox0');

  I.checkOption('//*[@id="access-checkbox0"]')

#### What do you get instead?

Element not visible

> Provide test source code if related

page element:
<div class="flex items-center mb2"><div class="checkbox dib"><input type="checkbox" id="access-checkbox0" value="Depositing funds"><label for="access-checkbox0"></label></div><span class="pl3">Depositing funds</span></div>

 Test Script:
     I.click('//*[@id="account-nav"]/li[3]/a');
        I.checkOption('#toggle-trading');
        I.click('SET IT UP');//TODO need unique name 
        I.wait(3);
        I.checkOption('#access-checkbox0'); --> use with I.click()
        I.checkOption('#access-checkbox1'); --> use with I click()  still not working

### Details

* CodeceptJS version: 1.1
* NodeJS Version:
* Operating System: MAC
* webdriverIO

**Comment by besrabasant** [comment] 2018-02-28 05:25
I am also facing the same issue. anyone with any workaround?

**Comment by reubenmiller** [comment] 2018-02-28 05:38
@besrabasant Can you provide the —verbose output your your test?

**Comment by besrabasant** [comment] 2018-02-28 05:52
@reubenmiller 
```
 'Start' button is enabled on checking 'Accept' checkbox
   Emitted | test.before
   [1] Queued | hook WebDriverIO._before()
   Emitted | test.start ([object Object])
   Emitted | step.before (I check option "#accept-agreement")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | checkOption: "#accept-agreement"
   Emitted | step.after (I check option "#accept-agreement")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   Emitted | step.before (I see checkbox is checked "#accept-agreement")
   [1] Queued | hook WebDriverIO._beforeStep()
   [1] Queued | seeCheckboxIsChecked: "#accept-agreement"
   Emitted | step.after (I see checkbox is checked "#accept-agreement")
   [1] Queued | hook WebDriverIO._afterStep()
   [1] Queued | step passed
   [1] Queued | return result
   [1] Queued | fire test.passed
   [1] Queued | finish test
   Emitted | step.start (I check option "#accept-agreement")
 • I check option "#accept-agreement"
   Emitted | step.passed (I check option "#accept-agreement")
   Step finished in 0.147 sec
   Emitted | step.start (I see checkbox is checked "#accept-agreement")
 • I see checkbox is checked "#accept-agreement"
   [1] Error | Error
   Emitted | step.failed (I see checkbox is checked "#accept-agreement")
   Step finished in 0.062 sec
   [1] Error | Error
   [1] Starting <teardown> session
   Emitted | test.failed ([object Object])
   [1] <teardown> Queued | hook WebDriverIO._failed()
   [1] <teardown> Queued | () => done(err)
   [1] <teardown> Stopping recording promises
 > Screenshot has been saved to /media/programmersedge/New_Volume/devs/frontend-e2e/logs/'Start'_button_is_enabled_on_checking_'Accept'_checkbox.failed.png
 ✖ FAILED in 800ms

```
```
- FAILURES:

  1) Agreements
       'Start' button is enabled on checking 'Accept' checkbox:

      expected checkable field #accept-agreement to be checked
      + expected - actual

      -false
      +true


  Scenario Steps:

  - I.seeCheckboxIsChecked("#accept-agreement") at Test.Scenario (__tests__/aggrements.test.ts:59:11)
  - I.checkOption("#accept-agreement") at Test.Scenario (__tests__/aggrements.test.ts:58:11)

  undefined

```

**Comment by reubenmiller** [comment] 2018-02-28 06:11
I am guesssing that it has something to do with either the html or maybe something is resetting this value. So can you try the following in a interactive shell (i.e. starting by using `codeceptjs shell`)

I ran the following code (similar to your test)
```sh
I.amOnPage('https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/checkbox/checkbox-2/checkbox-2.html')
I.checkOption('#cond1')
I.seeCheckcheckOption('#cond1')
I.seeCheckboxIsChecked('#cond1')
I.click('#cond1')
I.dontSeeCheckboxIsChecked('#cond1')
```

**Comment by besrabasant** [comment] 2018-02-28 07:42
@reubenmiller It's strange. When I run my test in the interactive shell, all _steps_ run fine. while in _test files_ the _test_ fail. And even the steps you provided above run fine using _test files_.  BTW, my frontend is in **React**, I don't think that should be a problem.

**Comment by reubenmiller** [comment] 2018-02-28 09:35
Maybe you need to add a delay before reading the item then. Maybe if you can provide an example with a react page then I can also use it for testing.

**Comment by besrabasant** [comment] 2018-02-28 10:15
I tried running these set of action. These run fine.
```
   I.amOnPage('http://react-component.github.io/checkbox/examples/simple.html')
    I.wait(3)
    I.seeElement('[name="my-checkbox"]')
    I.seeCheckboxIsChecked('.rc-checkbox > [name="my-checkbox"]')
    I.click('.rc-checkbox > [name="my-checkbox"]')
    I.dontSeeCheckboxIsChecked('.rc-checkbox > [name="my-checkbox"]')
```

**Comment by besrabasant** [comment] 2018-02-28 10:33
@reubenmiller I figured out what the issue is.  Actually, I am performing the checkbox operation on a pop-up window that I am opening using **React Portal**. Now when I switch to the _popup window_ the _main window_ gets closed. and therefore my checkbox that is in **React** does not respond to any operations.

**Comment by besrabasant** [comment] 2018-02-28 10:50
@reubenmiller  Solved the Issue. Just had to add these **two** in my _CodeceptJS_ config
```
{
   // other config
    "helpers": {
        "WebDriverIO": {
            // driver specific config
            "restart": false,
            "keepBrowserState": true,
        }
    }
}
```
I suppose we should close this issue now.

**Closed** 2018-02-28 11:21 UTC
