### ISSUE TITLE
[BUG] Video option with CodeceptJS and Playwright

### ISSUE THREAD

**Issue by Miriambnzdn** [Codeception/CodeceptJS#3396] opened 2022-08-24 10:44 UTC
Hello, 
I'm using CodeceptJS with Playwright as helper. 
When I activate the "video" option and my scenarios are played, I can see a .webm file in the "output/video" folder. But when my scenario ends with a failure, the file disappears and it is impossible to find it again. 

Does anyone have any idea what is going on?

**Comment by nicostubi** [comment] 2022-08-24 19:13
Don't you have a teardown script or similar that is deleting the ouput?

I use CodeceptJS with Playwright and I see videos after tests have failed.

**Comment by Miriambnzdn** [comment] 2022-09-01 06:56
Hi, Nope I don't have anything. 
And it's strange because I didn't have this problem before the upgrade from 3.3.3 to 3.3.4.

**Comment by Miriambnzdn** [comment] 2022-09-02 10:27
How do you implement this option?

**Comment by Miriambnzdn** [comment] 2022-09-08 07:47
No answer ?

**Comment by Miriambnzdn** [comment] 2022-09-22 07:11
???

**Comment by nicostubi** [comment] 2022-09-22 08:50
can you clarify your latest question ? Which option do you want to implement ?

**Comment by Miriambnzdn** [comment] 2022-09-22 13:31
Hi, as I say previously, I ask for video option. 
Can you please explain me how you implement this option because that doesn't work for me

**Comment by nicostubi** [comment] 2022-09-22 15:41
As specified in the documentation: https://codecept.io/playwright/#video

Sorry, we can only imagine you have the proper config. But we don't know the configuration you are using, nor we have a repro project.

The minimum would be to follow the template when creating a new issue, this would save us a lot of time and this would help us to help you.

BR
Nicolas

**Comment by Miriambnzdn** [comment] 2022-09-23 07:14
I don't share my config because she's lambda. This is my config : 
<img width="568" alt="Capture d’écran 2022-09-23 à 09 07 58" src="https://user-images.githubusercontent.com/94960638/191909071-3a140c89-e597-417e-b671-d853d395c748.png">

Where can I find the template you talking about ?

**Comment by nicostubi** [comment] 2022-09-24 08:13
Your configuration is incomplete. On mine, I have the setting "tests:" above the output. And I don't know what you have within your variable process.env.profile.

Assuming your configuration is correct (but with a partial example and no repro project, not easy to say), this is exactly what I am using as well to have output videos. But I doubt your config is correct. When I remove this line on my config (the one just above output):

`tests: './tests/*/**_test.ts',`

I have 0 tests passed.

When you have a failed test, do you see any screenshots within your output folder ?

Here is the template. As you will see, the template is asking for your config file. If you follow (I recommend you to start from scratch with a brand new issue and a clear title about what the problem actually is, or what you think it is):

![image](https://user-images.githubusercontent.com/47106274/192087555-8e163ad2-8090-4c35-9220-48acbe977ec6.png)

Also remember you have the code source here on github, so you may implement your configuration in a test/repro project (that you could share here if really not working). There is even a "CodeceptJS TypeScript Boilerplate" project to speed up things:  https://github.com/codeceptjs/typescript-boilerplate

**Comment by Miriambnzdn** [comment] 2022-09-26 07:12
Hi, 
my config isn't complete. It's a partial example tu show you how I implement the option.  
I have an output folder with screenshots. 
You can see my entire config just here : 
<img width="568" alt="Capture d’écran 2022-09-26 à 09 09 17" src="https://user-images.githubusercontent.com/94960638/192214790-db39f63c-6835-4fdd-bc10-f124d3093fe4.png">

I use Gherkin for my tests. 
Ok thank you for all thus information.

**Comment by nicostubi** [comment] 2022-09-28 20:33
where is your video configuration?

**Comment by Miriambnzdn** [comment] 2022-09-30 07:07
This is my configuration without option video, this is my configuration with video option : 
<img width="575" alt="Capture d’écran 2022-09-30 à 09 04 22" src="https://user-images.githubusercontent.com/94960638/193211085-4e8cdb3d-eafb-4f52-9f7d-94a074c63400.png">

I also tried with Trace option and that work very well. 
I don't understand why video option doesn't.

**Comment by kobenguyent** [comment] 2022-09-30 07:13
@Miriambnzdn try my simple test with playwright to see if video is generated for you. I could see video generated from my end. 

https://github.com/PeterNgTr/codeceptjs-playwright-fun

**Comment by ua1wcz** [comment] 2023-03-13 12:32
maybe I create a duplicate of this bug:
https://github.com/codeceptjs/CodeceptJS/issues/3614

**Comment by kobenguyent** [comment] 2023-10-19 12:51
Closed for now! Feel free to reopen if you still encounter the issue with latest version and would be nice to provide a sample code to reproduce the issue.

**Closed as completed by kobenguyent** 2023-10-19 12:51 UTC
