### ISSUE TITLE
Testing window popups created via window.open API

### ISSUE THREAD

**Issue by sidsarasvati** [Codeception/CodeceptJS#228] opened 2016-09-13 22:49 UTC
Hi, is there a way I can test a window popout behavior in my app? Basically, I want to assert that the app created a popup window as expected. The popout is created using the window.open() API. 

Some googling revealed the  PHP codeception had a I->swithToWindow() API method to switch between windows during testing. I think having such API will enable popup and secondary window testing use cases.

**Comment by APshenkin** [comment] 2017-06-01 10:47
duplicate of https://github.com/Codeception/CodeceptJS/issues/207

**Closed by APshenkin** 2017-06-01 10:47 UTC
