### ISSUE TITLE
v1.4.5 screenshots are no longer taken when we run-multiple

### ISSUE THREAD

**Issue by xMutaGenx** [Codeception/CodeceptJS#1317] opened 2018-11-07 11:24 UTC
#### What are you trying to achieve?

Framework takes a screenshot after failure on v1.4.5, works fine on v1.4.4

#### What do you get instead?

no screenshot is taken

### Details

* CodeceptJS version: 1.4.5
* NodeJS Version: >=8.9.1
* Operating System: OSX
* WebDriverIO: 4.14.0
* Configuration file:

```js
helpers: {
        WebDriverIO: {
          ...
          fullPageScreenshots: true,
          uniqueScreenshotNames: true,
          ...
       },
        Mochawesome: { uniqueScreenshotNames: true }
    }
```

**Comment by PeterNgTr** [comment] 2018-11-13 11:01
<img width="905" alt="screen shot 2018-11-13 at 11 59 54 am" src="https://user-images.githubusercontent.com/7845001/48409304-c17bc180-e73b-11e8-9737-a90bef74fd94.png">
Cannot reproduce this. It worked for me

**Comment by xMutaGenx** [comment] 2018-11-16 13:57
Hi @PeterNgTr the screenshot gets generated, it does not get attached to the report, so if you open up the mochawesome.html it won't be there, also, we use a specific output directory, with `run-multiple`, rather than just `run`

**Comment by PeterNgTr** [comment] 2018-11-19 14:11
![screenshot from 2018-11-19 15-11-23](https://user-images.githubusercontent.com/7845001/48712178-694a3100-ec0d-11e8-84d6-4ecba773d36f.png)
I can see the attached image for failed case.

**Comment by PeterNgTr** [comment] 2018-11-19 14:14
![screenshot from 2018-11-19 15-14-05](https://user-images.githubusercontent.com/7845001/48712332-c9d96e00-ec0d-11e8-8b9e-73cf201d74dc.png)
`run-multiple` also worked for me

**Comment by xMutaGenx** [comment] 2018-11-19 14:53
@PeterNgTr just to confirm before I go digging through our stack, which version of grid/hub are you using?

**Comment by PeterNgTr** [comment] 2018-11-19 14:57
I'm running against `puppeteer`

**Comment by xMutaGenx** [comment] 2018-11-19 15:40
Ah, we've got a grid/hub setup of v3.141.5, will take a look if that is causing it as well, thanks for the info though!

**Comment by yogainalift** [comment] 2018-11-21 12:20
I can also confirm that for 1.4.6 the screenshots are not even generated and not attached to the form. Reverted back to 1.4.4 for now.

**Comment by mirao** [comment] 2018-11-23 12:19
Confirmed. Since 1.4.5 both commands `run` and `run-multiple` are affected. No screenshot is done on failure. 
Tested with WebDriverIO

**Comment by PredragPavlovic** [comment] 2018-11-27 08:10
@PeterNgTr I suppose that you don't have problem because you use **Puppeteer** but it is the last helper on the list (https://github.com/Codeception/CodeceptJS/blob/master/lib/plugin/screenshotOnFail.js#L15). Could you move **Mochawesome** on the bottom of the list and try if it will work correctly for you? I think **Mochawesome** should be removed from _supportedHelpers_ list and problem will be fixed.

**Comment by mirao** [comment] 2018-11-27 15:24
Confirmed @PredragPavlovic's info.
This order works for me:
```javascript
const supportedHelpers = [
  'Mochawesome',
  'WebDriverIO',
  'Protractor',
  'Appium',
  'Nightmare',
  'Puppeteer',
];
```

**Comment by PeterNgTr** [comment] 2018-11-28 15:54
Fix is on the way -> https://github.com/Codeception/CodeceptJS/pull/1354

**Closed** 2018-12-05 12:07 UTC
