### ISSUE TITLE
Puppeteer - cannot run more than one scenario

### ISSUE THREAD

**Issue by awshanks** [Codeception/CodeceptJS#965] opened 2018-02-26 10:11 UTC
#### What are you trying to achieve?

Run more than one scenario in a feature.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
Open Github @sample --
 open browser and navigate to github.com
 • I am on page "https://github.com/awshanks"
 • I click "codecept_training_material"
 ✓ OK in 8435ms

 ✖ "after each" hook: finalize codeceptjs for "open browser and navigate to github.com" in 458ms
TypeError: this.browser.execute is not a function

-- FAILURES:

  1) Open Github @sample
       "after each" hook: finalize codeceptjs for "open browser and navigate to github.com":
     this.browser.execute is not a function


```

> Provide test source code if related

```js
'use strict';

Feature('Open Github @sample');

BeforeSuite((I) => {
});

Scenario('open browser and navigate to github.com', (I) => {
I.amOnPage('https://github.com/awshanks');
I.click('codecept_training_material');
I.getCurrentUrl().then(function (result) {
    console.log(result);
});
});

Scenario('open browser and navigate to google.co.uk', (I) => {
    I.amOnPage('https://github.com');
});

AfterSuite(() => {
});
```

### Details

* CodeceptJS version: 1.1.5 (puppeteer 1.1.0)
* NodeJS Version: 8.9.4
* Operating System: macOS
* Configuration file:

```js
'use strict';

exports.config = {
    "tests": "../integrationSpecs/examples/*.js",
    "timeout": 10000,
    "output": "../integrationSpecs/screenShots",
    "helpers": {
        "Puppeteer":{
            "url": "https://www.google.co.uk",
            "windowSize": "1920x1080",
            "waitForAction": 300,
            "restart": false,
            "show": true,
            "keepCookies": true,
            "chrome": {
                "ignoreHTTPSErrors": true,
                "devtools": true,
                "slowMo": 300,
            }
        }
    },
    "name": "codecept_template"
};

```

**Comment by reubenmiller** [comment] 2018-02-26 11:10
The error is due to the navigation action being caused by the click in the first scenario. It is causing an unhandled exception in the `After` step. If my suggestions are followed from #963, then this problem will go away.

**Comment by reubenmiller** [comment] 2018-02-26 12:53
@awshanks Can I close this ticket now as it is related to #963.

**Comment by reubenmiller** [comment] 2018-02-26 12:54
Duplicate of #705

**Closed by reubenmiller** 2018-02-26 12:54 UTC

**Comment by junguchina** [comment] 2018-02-27 08:06
Same issue with the error output like below:
```TypeError: this.browser.execute is not a function```
I find I do not use the ```click``` action, and all actions are offcial steps.
So I will create another issue.

**Comment by reubenmiller** [comment] 2018-02-27 09:17
Hi @junguchina, yes please create a new ticket.
