### ISSUE TITLE
How to access sqlite in our BDD test cases 

### ISSUE THREAD

**Issue by sumiagar** [Codeception/CodeceptJS#1973] opened 2019-10-18 06:21 UTC
Trying to Add dbhelper in my project

not able to install database-js sqlite

terminal stuck at 

PS C:\ws\N_TEST\NET_Codecept_Automation\NET_UI_Codecept_Automation> npm install --save-dev database-js-sqlite
[..................] - fetchMetadata: sill resolveWithNewModule database-js-sqlite@1.3.0 checking installable status

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

In my project, I have SQLite DB. I want to verify some data from database also. So I want to integrate sqlite in my test cases. for that I m following below link 

https://github.com/thiagodp/codeceptjs-dbhelper

but not able to install database-js sqlite 

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by pablopaul** [comment] 2019-10-18 12:56
@sumiagar you already asked in the right repo at, in the current repo please only report bugs related to CodeceptJS core, thanks

**Comment by Vorobeyko** [comment] 2019-11-04 16:35
@sumiagar Sorry, but I will close this issue because the problem is not in CodeceptJS =) Thank you!)

**Closed by Vorobeyko** 2019-11-04 16:35 UTC
